### ISSUE TITLE
Cloudformation does not add `StackName` to the `State machine` name

### ISSUE THREAD

**Issue by mskogorevrmc** [aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions#44]
I noticed that if I don't add StateMachineName in the template, then the name `State machines` is generated as follows:
[resource]-[uniqid]
but for all other resources in the template (Roles,LogGroup and etc), StackName is added to the name:
[stackname]-[resource]-[uniqid]

Is this a bug or is this how it should work? Thanks

**Comment by wong-a** [comment]
This is by design. CloudFormation does not prescribe a particular naming convention for physicalIds, other than that they should be unique. Do you have a use case requiring a particular naming convention?

This was discussed in a previous issue:
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions/issues/26#issuecomment-1472949187
